### PR TITLE
Add a storybook

### PR DESCRIPTION
**Pull request by contiki9**
---

### CODE REVIEW

**Comment by contiki9** [comment]
おそらく私はこれと同じ状況である
Perhaps I am in the same situation as this

https://github.com/ionic-team/stencil/issues/1675

**Comment by rdlabo** [comment]
@contiki9 Maybe https://github.com/ionic-team/ionicons/issues/670 is one of solutions.
If this trouble is only be at storybook, I recommend copy solution. 
Thanks.

**Comment by contiki9** [comment]
@rdlabo 

> If this trouble is only be at storybook, I recommend copy solution.
Thanks.

Thanks.

This file is a public file at [unpkg](https://github.com/stripe-elements/stripe-elements/blob/feature/add-storybook/package.json#L12), so It seems to affect more than just storybook.

ありがとう。

このファイルは[unpkg](https://github.com/stripe-elements/stripe-elements/blob/feature/add-storybook/package.json#L12)のところで公開しているファイルなのでstorybook以外でも影響がありそうです。

**Comment by rdlabo** [comment]
@contiki9 You should confirm effect area. I created @capacitor-community/stripe, but ion-icon is loaded. Thanks.

**Pull request closed without merging**
